# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=20)),
                ('comment_date', models.DateTimeField()),
                ('comment_content', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=80)),
                ('post_author', models.CharField(max_length=20)),
                ('date_posted', models.DateTimeField()),
                ('post_content', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billboardapp.Post'),
        ),
    ]
